<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `shezartc_elearning1`
//

// `shezartc_elearning1`.`topics`
$topics = array(
  array('topic_id' => '3DG','subject_id' => 'MAT','name' => '3D-Geometry','info' => '3D-Geometry'),
  array('topic_id' => 'A  J L','subject_id' => 'PHY','name' => 'Electromagnetic Induction','info' => 'Electromagnetic Induction'),
  array('topic_id' => 'A B C','subject_id' => 'CHE','name' => 'Magnetic Effects of Current','info' => 'Magnetic Effects of Current'),
  array('topic_id' => 'aaa','subject_id' => 'MAT','name' => 'FUNCTIONS','info' => 'FUNCTIONS'),
  array('topic_id' => 'AAH','subject_id' => 'CHE','name' => 'Alkyl And Aryl Halides','info' => 'Alkyl And Aryl Halides'),
  array('topic_id' => 'AAZ','subject_id' => 'CHE','name' => 'METALLURGICAL EXTRACTION','info' => 'METALLURGICAL EXTRACTION'),
  array('topic_id' => 'abc','subject_id' => 'MAT','name' => 'APPLICATIONS OF DERIVATIES','info' => 'APPLICATIONS OF DERIVATIES'),
  array('topic_id' => 'ADS','subject_id' => 'CHE','name' => 'solution and colligative properties','info' => 'solution and colligative properties'),
  array('topic_id' => 'AEA','subject_id' => 'MAT','name' => 'ALGEBRA','info' => 'ALGEBRA'),
  array('topic_id' => 'AED','subject_id' => 'CHE','name' => 'THERMODYNAMICS','info' => 'THERMODYNAMICS'),
  array('topic_id' => 'AEP','subject_id' => 'CHE','name' => 'Alcohol, Ether and Phenol','info' => 'Alcohol, Ether and Phenol'),
  array('topic_id' => 'AFE','subject_id' => 'CHE','name' => 'some basic concepts of chemistry','info' => 'some basic concepts of chemistry'),
  array('topic_id' => 'AKN','subject_id' => 'CHE','name' => 'Aldehyde & Ketone','info' => 'Aldehyde & Ketone'),
  array('topic_id' => 'AMs','subject_id' => 'CHE','name' => 'AMINES','info' => 'AMINES'),
  array('topic_id' => 'ANC','subject_id' => 'CHE','name' => 'Analytical Chemistry','info' => 'Analytical Chemistry'),
  array('topic_id' => 'ANZ','subject_id' => 'CHE','name' => 'SALT ANALYSIS','info' => 'SALT ANALYSIS'),
  array('topic_id' => 'ara','subject_id' => 'MAT','name' => 'Area','info' => 'Area'),
  array('topic_id' => 'ASF','subject_id' => 'MAT','name' => 'INTEGRAL CALCULUS','info' => 'INTEGRAL CALCULUS'),
  array('topic_id' => 'ATS','subject_id' => 'CHE','name' => 'Atomic Structure','info' => 'Atomic structure'),
  array('topic_id' => 'AYL','subject_id' => 'CHE','name' => 'ANALYTICAL','info' => 'ANALYTICAL'),
  array('topic_id' => 'B G K','subject_id' => 'PHY','name' => 'Electromagnetic Induction','info' => 'Electromagnetic Induction'),
  array('topic_id' => 'BBB','subject_id' => 'MAT','name' => 'PROBABILITY','info' => 'PROBABILITY'),
  array('topic_id' => 'BGB','subject_id' => 'PHY','name' => 'General','info' => 'General'),
  array('topic_id' => 'BINO','subject_id' => 'MAT','name' => ' BINOMIAL THEOREM','info' => '.BINOMIAL THEOREM'),
  array('topic_id' => 'BNM','subject_id' => 'CHE','name' => 'EXTRACTIVE METALLURGY','info' => 'EXTRACTIVE METALLURGY'),
  array('topic_id' => 'BXW','subject_id' => 'CHE','name' => 'INORGANIC CHEMISTRY','info' => 'INORGANIC CHEMISTRY'),
  array('topic_id' => 'C Am','subject_id' => 'CHE','name' => 'Carbohydrates , Amino acids , Polymers & Miscellaneous','info' => 'Carbohydrates , Amino acids , Polymers & Miscellaneous'),
  array('topic_id' => 'CAB','subject_id' => 'CHE','name' => 'CONCEPTS OF ACIDS & BASES','info' => 'CONCEPTS OF ACIDS & BASES'),
  array('topic_id' => 'CAD','subject_id' => 'CHE','name' => 'CARBOXYLIC ACID & ITS DERIVATIVES','info' => 'CARBOXYLIC ACID & ITS DERIVATIVES'),
  array('topic_id' => 'CAP','subject_id' => 'CHE','name' => 'carbohydrates, amino acids & polymers','info' => 'carbohydrates, amino acids & polymers'),
  array('topic_id' => 'CCO','subject_id' => 'CHE','name' => 'Compounds Containing Oxygen','info' => 'Compounds Containing Oxygen'),
  array('topic_id' => 'CCP','subject_id' => 'CHE','name' => 'CONCEPT','info' => 'CONCEPT'),
  array('topic_id' => 'CEE','subject_id' => 'CHE','name' => 'Chemical Equilibrium & Ionic Equilibrium','info' => 'Chemical Equilibrium & Ionic Equilibrium'),
  array('topic_id' => 'CEM','subject_id' => 'CHE','name' => 'Chemical Equilibrium','info' => 'Chemical Equilibrium'),
  array('topic_id' => 'ChE','subject_id' => 'CHE','name' => 'Chemical Enegetics','info' => 'Chemical Energetics'),
  array('topic_id' => 'CHI','subject_id' => 'CHE','name' => 'Chemical Equilibrium','info' => 'Chemical Equilibrium'),
  array('topic_id' => 'CIR','subject_id' => 'MAT','name' => 'CIRCLE','info' => 'CIRCLE'),
  array('topic_id' => 'CLB','subject_id' => 'CHE','name' => 'Chemical Bonding','info' => 'Chemical Bonding'),
  array('topic_id' => 'CMA','subject_id' => 'CHE','name' => 'HYDROGEN AND ITS COMPOUNDS','info' => 'HYDROGEN AND ITS COMPOUNDS'),
  array('topic_id' => 'CMR','subject_id' => 'PHY','name' => 'Circular Motion and Rotation','info' => 'Circular Motion and Rotation'),
  array('topic_id' => 'CNM','subject_id' => 'PHY','name' => 'Center of Mass, Impulse and Momentum','info' => 'Center of Mass, Impulse and Momentum'),
  array('topic_id' => 'CNP','subject_id' => 'CHE','name' => 'Compounds Containing Nitrogen & Practical Organic Chemistry','info' => 'Compounds Containing Nitrogen & Practical Organic Chemistry'),
  array('topic_id' => 'CNS','subject_id' => 'CHE','name' => 'Chemical Kinetics','info' => 'Chemical Kinetics'),
  array('topic_id' => 'COC','subject_id' => 'CHE','name' => 'Coordination Compounds','info' => 'Coordination Compounds'),
  array('topic_id' => 'COM','subject_id' => 'MAT','name' => ' COMPLEX NUMBERS','info' => ' COMPLEX NUMBERS'),
  array('topic_id' => 'COO','subject_id' => 'MAT','name' => 'Straight Line','info' => 'Straight Line'),
  array('topic_id' => 'Coor','subject_id' => 'MAT','name' => 'Coordinate Geometry','info' => 'Coordinate Geometry'),
  array('topic_id' => 'CRN','subject_id' => 'CHE','name' => 'CARBON','info' => 'CARBON'),
  array('topic_id' => 'CTEST','subject_id' => 'CHE','name' => 'Chemistry test','info' => 'test'),
  array('topic_id' => 'CUS','subject_id' => 'MAT','name' => 'CALCULUS','info' => 'CALCULUS'),
  array('topic_id' => 'DaA','subject_id' => 'PHY','name' => 'General','info' => 'General'),
  array('topic_id' => 'DEA','subject_id' => 'CHE','name' => 'Dimensions and Error Analysis','info' => 'Dimensions and Error Analysis'),
  array('topic_id' => 'DEF','subject_id' => 'MAT','name' => 'DEFINITE INTEGRALS','info' => 'DEFINITE INTEGRALS'),
  array('topic_id' => 'Det','subject_id' => 'MAT','name' => 'DETERMINANTS','info' => 'DETERMINANTS '),
  array('topic_id' => 'DEU','subject_id' => 'CHE','name' => 'SOLUTION','info' => 'SOLUTION'),
  array('topic_id' => 'DIFFERENTIAL CALCULUS','subject_id' => 'MAT','name' => 'DIFFERENTIAL CALCULUS','info' => 'DIFFERENTIAL CALCULUS'),
  array('topic_id' => 'DLD','subject_id' => 'CHE','name' => 'CHEMICAL BOND','info' => 'CHEMICAL BOND'),
  array('topic_id' => 'DLE','subject_id' => 'MAT','name' => ' DETERMINANTS AND LINEAR EQUATIONS','info' => ' DETERMINANTS AND LINEAR EQUATIONS'),
  array('topic_id' => 'DOD','subject_id' => 'PHY','name' => 'Electromagnetic Induction','info' => 'Electromagnetic Induction'),
  array('topic_id' => 'E A.C.','subject_id' => 'PHY','name' => 'Electromagnetic Induction','info' => 'Electromagnetic Induction'),
  array('topic_id' => 'EAM','subject_id' => 'PHY','name' => 'Elasticity & Fluid Mechanics','info' => 'Elasticity & Fluid Mechanics'),
  array('topic_id' => 'EAR','subject_id' => 'CHE','name' => 'NUCLEAR CHEMISTRY','info' => 'NUCLEAR CHEMISTRY'),
  array('topic_id' => 'EAS','subject_id' => 'CHE','name' => 'Electrophilic Aromatic Substitution','info' => 'Electrophilic Aromatic Substitution'),
  array('topic_id' => 'ELLI','subject_id' => 'MAT','name' => ' ELLIPSE','info' => ' ELLIPSE'),
  array('topic_id' => 'Elo','subject_id' => 'CHE','name' => 'Electrochemistry','info' => 'Elo'),
  array('topic_id' => 'EM','subject_id' => 'PHY','name' => 'Electricity & Magnetism','info' => 'Electricity & Magnetism'),
  array('topic_id' => 'EMB','subject_id' => 'CHE','name' => 'Extraction of Metals & s-Block Elements','info' => 'Extraction of Metals & s-Block Elements'),
  array('topic_id' => 'Ene','subject_id' => 'CHE','name' => 'Energetics','info' => 'Energetics'),
  array('topic_id' => 'Error','subject_id' => 'PHY','name' => 'General','info' => 'General'),
  array('topic_id' => 'FGO','subject_id' => 'CHE','name' => 'THERMODYNAMICS AND CHEMICAL ENERGETICS','info' => 'THERMODYNAMICS AND CHEMICAL ENERGETICS'),
  array('topic_id' => 'FHF','subject_id' => 'CHE','name' => 'STOICHIOMETRY AND OXIDATION/REDUCTION','info' => 'STOICHIOMETRY AND OXIDATION/REDUCTION'),
  array('topic_id' => 'FLF','subject_id' => 'CHE','name' => 'BORON','info' => 'BORON'),
  array('topic_id' => 'FMC','subject_id' => 'PHY','name' => 'Elasticity & Fluid Mechanics','info' => 'Elasticity & Fluid Mechanics'),
  array('topic_id' => 'GLS','subject_id' => 'CHE','name' => 'Gaseous & Liquid State','info' => 'Gaseous & Liquid State'),
  array('topic_id' => 'go','subject_id' => 'MAT','name' => 'Trigonometry','info' => 'Trigonometry'),
  array('topic_id' => 'GOC','subject_id' => 'CHE','name' => 'General Organic Chemistry & Isomerism','info' => 'General Organic Chemistry & Isomerism'),
  array('topic_id' => 'GOs','subject_id' => 'PHY','name' => 'Optics','info' => 'Optics'),
  array('topic_id' => 'GR','subject_id' => 'PHY','name' => 'Gravitation','info' => 'Gravitation'),
  array('topic_id' => 'Gra','subject_id' => 'PHY','name' => 'Gravitation','info' => 'Gravitation'),
  array('topic_id' => 'GSA','subject_id' => 'CHE','name' => 'Gaseous State','info' => 'Gaseous State'),
  array('topic_id' => 'GTY','subject_id' => 'MAT','name' => 'GEOMETRY','info' => 'GEOMETRY'),
  array('topic_id' => 'HaT','subject_id' => 'PHY','name' => 'Thermal Physics','info' => 'Thermal Physics'),
  array('topic_id' => 'HCN','subject_id' => 'CHE','name' => 'HYDROXY COMPOUNDS','info' => 'HYDROXY COMPOUNDS'),
  array('topic_id' => 'HFT','subject_id' => 'PHY','name' => 'Electromagnetic Induction','info' => 'Electromagnetic Induction'),
  array('topic_id' => 'HHD','subject_id' => 'CHE','name' => 'Hydrocarbon & Halogen Derivatives','info' => 'Hydrocarbon & Halogen Derivatives'),
  array('topic_id' => 'HHH','subject_id' => 'PHY','name' => 'Thermal Physics','info' => 'Thermal Physics'),
  array('topic_id' => 'HOE','subject_id' => 'CHE','name' => 'HALOGEN','info' => 'HALOGEN'),
  array('topic_id' => 'HOH','subject_id' => 'PHY','name' => 'Thermal Physics','info' => 'Thermal Physics'),
  array('topic_id' => 'HPS','subject_id' => 'CHE','name' => 'HALOGEN COMPOUNDS','info' => 'HALOGEN COMPOUNDS'),
  array('topic_id' => 'Hyn','subject_id' => 'CHE','name' => 'Hydrocarbons','info' => 'Hydrocarbons'),
  array('topic_id' => 'HYPER','subject_id' => 'MAT','name' => 'HYPERBOLA','info' => 'HYPERBOLA'),
  array('topic_id' => 'IEM','subject_id' => 'CHE','name' => 'Ionic Equilibrium','info' => 'Ionic Equilibrium'),
  array('topic_id' => 'IMp','subject_id' => 'PHY','name' => 'Center of Mass, Impulse and Momentum','info' => 'Center of Mass, Impulse and Momentum'),
  array('topic_id' => 'inverse','subject_id' => 'MAT','name' => 'INVERSE TRIGONOMETRIC FUNCTIONS','info' => 'INVERSE TRIGONOMETRIC FUNCTIONS'),
  array('topic_id' => 'IOH','subject_id' => 'PHY','name' => 'Kinematics','info' => 'Kinematics'),
  array('topic_id' => 'JHJ','subject_id' => 'PHY','name' => 'Optics','info' => 'Optics'),
  array('topic_id' => 'K L T','subject_id' => 'PHY','name' => 'Electricity & Magnetism','info' => 'Electricity & Magnetism'),
  array('topic_id' => 'KHR','subject_id' => 'PHY','name' => 'Optics','info' => 'Optics'),
  array('topic_id' => 'kkk','subject_id' => 'MAT','name' => 'Trigonometric  Equations and Inequations','info' => 'Trigonometric  Equations and Inequations'),
  array('topic_id' => 'KM','subject_id' => 'PHY','name' => 'Kinematics','info' => 'Kinematics'),
  array('topic_id' => 'KPK','subject_id' => 'PHY','name' => 'Optics','info' => 'Optics'),
  array('topic_id' => 'KTG','subject_id' => 'PHY','name' => 'Center of Mass, Impulse and Momentum','info' => 'Center of Mass, Impulse and Momentum'),
  array('topic_id' => 'KTU','subject_id' => 'PHY','name' => 'Physics Test','info' => 'Physics Test'),
  array('topic_id' => 'KVP','subject_id' => 'CHE','name' => 'PHYSICAL CHEMISTRY','info' => 'PHYSICAL CHEMISTRY'),
  array('topic_id' => 'KXD','subject_id' => 'CHE','name' => 'STOICHIOMETRY AND REDOX REACTIONS','info' => 'STOICHIOMETRY AND REDOX REACTIONS'),
  array('topic_id' => 'LCD','subject_id' => 'MAT','name' => 'Limits , Continuity and Diffretiablitiy','info' => 'Limits , Continuity and Diffretiablitiy'),
  array('topic_id' => 'LFI','subject_id' => 'PHY','name' => 'Electromagnetic Induction','info' => 'Electromagnetic Induction'),
  array('topic_id' => 'Liquid','subject_id' => 'CHE','name' => 'Liquid Solutions','info' => 'Liquid Solutions'),
  array('topic_id' => 'LLP','subject_id' => 'PHY','name' => 'Kinematics','info' => 'Kinematics'),
  array('topic_id' => 'LM','subject_id' => 'PHY','name' => 'Law of Motion','info' => 'Law of Motion'),
  array('topic_id' => 'LMF','subject_id' => 'PHY','name' => 'Law of Motion','info' => 'Law of Motion'),
  array('topic_id' => 'LOG','subject_id' => 'MAT','name' => 'LOGARITHMS','info' => 'LOGARITHMS'),
  array('topic_id' => 'LOL','subject_id' => 'PHY','name' => 'Electricity & Magnetism','info' => 'Electricity & Magnetism'),
  array('topic_id' => 'LOT','subject_id' => 'PHY','name' => 'Modern Physics','info' => 'Modern Physics'),
  array('topic_id' => 'LPO','subject_id' => 'PHY','name' => 'Modern Physics','info' => 'Modern Physics'),
  array('topic_id' => 'LQS','subject_id' => 'CHE','name' => 'Liquid Solution','info' => 'Liquid Solution'),
  array('topic_id' => 'LSN','subject_id' => 'CHE','name' => 'Liquid Solution','info' => 'Liquid Solution'),
  array('topic_id' => 'Mag','subject_id' => 'PHY','name' => 'Electricity & Magnetism','info' => 'Electricity & Magnetism'),
  array('topic_id' => 'MAT','subject_id' => 'MAT','name' => 'MATRICES','info' => 'MATRICES'),
  array('topic_id' => 'maths','subject_id' => 'MAT','name' => 'maths euqation','info' => 'maths equation'),
  array('topic_id' => 'MCS','subject_id' => 'CHE','name' => 'Mole Concept & Stoichiometry','info' => 'Mole Concept & Stoichiometry'),
  array('topic_id' => 'MIC','subject_id' => 'CHE','name' => 'Mathematics in chemistry','info' => 'Mathematics in chemistry'),
  array('topic_id' => 'MKM','subject_id' => 'PHY','name' => 'Modern Physics','info' => 'Modern Physics'),
  array('topic_id' => 'MNB','subject_id' => 'CHE','name' => 'ISOMERISM','info' => 'ISOMERISM'),
  array('topic_id' => 'Modern','subject_id' => 'PHY','name' => 'Modern Physics','info' => 'Modern Physics'),
  array('topic_id' => 'MOP','subject_id' => 'CHE','name' => 'ALKALINE EARTH METALS','info' => 'ALKALINE EARTH METALS'),
  array('topic_id' => 'Mtd','subject_id' => 'PHY','name' => 'Law of Motion','info' => 'Law of Motion'),
  array('topic_id' => 'MTEST','subject_id' => 'MAT','name' => 'Maths Test','info' => 'test'),
  array('topic_id' => 'New','subject_id' => 'PHY','name' => 'Law of Motion','info' => 'Law of Motion'),
  array('topic_id' => 'newton','subject_id' => 'PHY','name' => 'Law of Motion','info' => 'Law of Motion'),
  array('topic_id' => 'NTG','subject_id' => 'CHE','name' => 'NITROGEN','info' => 'NITROGEN'),
  array('topic_id' => 'O P F','subject_id' => 'PHY','name' => 'Electricity & Magnetism','info' => 'Electricity & Magnetism'),
  array('topic_id' => 'OAM','subject_id' => 'CHE','name' => 'ORES AND METALLURGY','info' => 'ORES AND METALLURGY'),
  array('topic_id' => 'OEQ','subject_id' => 'CHE','name' => 'ALKALI METALS','info' => 'ALKALI METALS'),
  array('topic_id' => 'OGC','subject_id' => 'CHE','name' => 'General Organic Chemistry','info' => 'General Organic Chemistry'),
  array('topic_id' => 'OLO','subject_id' => 'PHY','name' => 'Work, Energy and Power','info' => 'Work, Energy and Power'),
  array('topic_id' => 'OPD','subject_id' => 'PHY','name' => 'Electromagnetic Induction','info' => 'Electromagnetic Induction'),
  array('topic_id' => 'OPO','subject_id' => 'PHY','name' => 'Elasticity & Fluid Mechanics','info' => 'Elasticity & Fluid Mechanics'),
  array('topic_id' => 'OPT','subject_id' => 'PHY','name' => 'Optics','info' => 'Optics'),
  array('topic_id' => 'orc','subject_id' => 'CHE','name' => 'ORGANIC CHEMISTRY','info' => 'ORGANIC CHEMISTRY'),
  array('topic_id' => 'OSS','subject_id' => 'PHY','name' => 'Simple Harmonic Motion','info' => 'Simple Harmonic Motion'),
  array('topic_id' => 'OUG','subject_id' => 'PHY','name' => 'Gravitation','info' => 'Gravitation'),
  array('topic_id' => 'OXN','subject_id' => 'CHE','name' => 'OXYGEN','info' => 'OXYGEN'),
  array('topic_id' => 'P A T','subject_id' => 'MAT','name' => 'PROPERTIES AND SOLUTIONS OF TRIANGLES ','info' => ' PROPERTIES AND SOLUTIONS OF TRIANGLES '),
  array('topic_id' => 'p-BO','subject_id' => 'CHE','name' => 'p-Block Elements','info' => 'p-Block Elements'),
  array('topic_id' => 'PARA','subject_id' => 'MAT','name' => 'PARABOLA','info' => 'PARABOLA'),
  array('topic_id' => 'per','subject_id' => 'MAT','name' => 'PERMUTATION AND COMBINATION','info' => 'PERMUTATION AND COMBINATION'),
  array('topic_id' => 'PEU','subject_id' => 'PHY','name' => 'Modern Physics','info' => 'Modern Physics'),
  array('topic_id' => 'PNS','subject_id' => 'CHE','name' => 'CARBONYL COMPOUNDS','info' => 'CARBONYL COMPOUNDS'),
  array('topic_id' => 'poc','subject_id' => 'CHE','name' => 'practical organic chemistry','info' => 'practical organic chemistry'),
  array('topic_id' => 'POINT','subject_id' => 'MAT','name' => 'POINTS AND STRAIGHT LINES','info' => 'POINTS AND STRAIGHT LINES'),
  array('topic_id' => 'PPC','subject_id' => 'CHE','name' => 'PREPARATION AND PROPERTIES OF COMPOUNDS','info' => 'PREPARATION AND PROPERTIES OF COMPOUNDS'),
  array('topic_id' => 'PPP','subject_id' => 'PHY','name' => 'Simple Harmonic Motion','info' => 'Simple Harmonic Motion'),
  array('topic_id' => 'PPT','subject_id' => 'PHY','name' => 'Circular Motion and Rotation','info' => 'Circular Motion and Rotation'),
  array('topic_id' => 'PRO','subject_id' => 'MAT','name' => 'PROGRESSION AND  SERIES','info' => 'PROGRESSION AND  SERIES'),
  array('topic_id' => 'PTE','subject_id' => 'CHE','name' => 'Periodic Table','info' => 'Periodic Table'),
  array('topic_id' => 'PTEST','subject_id' => 'PHY','name' => 'Physics Test','info' => 'Physics Test'),
  array('topic_id' => 'QE','subject_id' => 'MAT','name' => 'Quadratic Equations, Inequations And Expressions ','info' => 'Quadratic Equations, Inequations And Expressions '),
  array('topic_id' => 'QGQ','subject_id' => 'PHY','name' => 'Waves','info' => 'Waves'),
  array('topic_id' => 'QUA','subject_id' => 'MAT','name' => 'QUADRATIC EQUATIONS','info' => 'QUADRATIC EQUATIONS'),
  array('topic_id' => 'QVA','subject_id' => 'CHE','name' => 'Qulitative Analysis','info' => 'Qualitative Analysis'),
  array('topic_id' => 'RKL','subject_id' => 'CHE','name' => 'NITROGEN COMPOUNDS, AMINO ACIDS AND CARBOHYDRATES','info' => 'NITROGEN COMPOUNDS, AMINO ACIDS AND CARBOHYDRATES'),
  array('topic_id' => 'RMS','subject_id' => 'PHY','name' => 'Circular Motion and Rotation','info' => 'Circular Motion and Rotation'),
  array('topic_id' => 'S& E','subject_id' => 'PHY','name' => 'Modern Physics','info' => 'Modern Physics'),
  array('topic_id' => 'SAD','subject_id' => 'CHE','name' => 'KINETICS','info' => 'KINETICS'),
  array('topic_id' => 'SAS','subject_id' => 'MAT','name' => 'SEQUENCES AND SERIES ','info' => 'SEQUENCES AND SERIES '),
  array('topic_id' => 'SAV','subject_id' => 'PHY','name' => 'Kinematics','info' => 'Kinematics'),
  array('topic_id' => 'SBL','subject_id' => 'CHE','name' => 'S-Block','info' => 'Description of S-block'),
  array('topic_id' => 'SDE','subject_id' => 'CHE','name' => 'LIQUID STATE','info' => 'LIQUID STATE'),
  array('topic_id' => 'SED','subject_id' => 'PHY','name' => 'Electricity & Magnetism','info' => 'Electricity & Magnetism'),
  array('topic_id' => 'SFD','subject_id' => 'CHE','name' => 'SURFACE CHEMISTRY','info' => 'SURFACE CHEMISTRY'),
  array('topic_id' => 'SHE','subject_id' => 'PHY','name' => 'Simple Harmonic Motion','info' => 'Simple Harmonic Motion'),
  array('topic_id' => 'Solid','subject_id' => 'PHY','name' => 'Elasticity & Fluid Mechanics','info' => 'Elasticity & Fluid Mechanics'),
  array('topic_id' => 'SOT','subject_id' => 'MAT','name' => 'SOLUTION  OF TRIANGLES','info' => 'SOLUTION  OF TRIANGLES'),
  array('topic_id' => 'SPS','subject_id' => 'PHY','name' => 'Electricity & Magnetism','info' => 'Electricity & Magnetism'),
  array('topic_id' => 'SSC','subject_id' => 'CHE','name' => 'Solid State & Surface Chemistry & Colloids','info' => 'Solid State & Surface Chemistry & Colloids'),
  array('topic_id' => 'SSt','subject_id' => 'CHE','name' => 'Solid State','info' => 'Solid State'),
  array('topic_id' => 'STO','subject_id' => 'CHE','name' => 'STOICHIOMETRY','info' => 'STOICHIOMETRY'),
  array('topic_id' => 'STR','subject_id' => 'MAT','name' => 'STRAIGHT LINES','info' => 'STRAIGHT LINES'),
  array('topic_id' => 'Surface','subject_id' => 'PHY','name' => 'Elasticity & Fluid Mechanics','info' => 'Elasticity & Fluid Mechanics'),
  array('topic_id' => 'SYS','subject_id' => 'PHY','name' => 'Center of Mass, Impulse and Momentum','info' => 'Center of Mass, Impulse and Momentum'),
  array('topic_id' => 'TCC','subject_id' => 'CHE','name' => 'Transition & Co-ordination Compounds','info' => 'Transition & Co-ordination Compounds'),
  array('topic_id' => 'Thermal','subject_id' => 'PHY','name' => 'Thermal Physics','info' => 'Thermal Physics'),
  array('topic_id' => 'THR','subject_id' => 'MAT','name' => 'THREE DIMENSIONAL GEOMETRY','info' => 'THREE DIMENSIONAL GEOMETRY'),
  array('topic_id' => 'THREE','subject_id' => 'MAT','name' => 'Three diamension','info' => 'Three diamension'),
  array('topic_id' => 'TNE','subject_id' => 'CHE','name' => 'TRANSITION ELEMENTS','info' => 'TRANSITION ELEMENTS'),
  array('topic_id' => 'TRE','subject_id' => 'MAT','name' => 'TRIGONOMETRIC EQUATIONS','info' => 'TRIGONOMETRIC EQUATIONS'),
  array('topic_id' => 'TRI','subject_id' => 'MAT','name' => 'TRIGONOMETRIC RATIOS AND IDENTITIES','info' => ''),
  array('topic_id' => 'TRIGO','subject_id' => 'MAT','name' => 'TRIGONOMETRIC FUNCTIONS','info' => 'TRIGONOMETRIC FUNCTIONS'),
  array('topic_id' => 'TWO','subject_id' => 'MAT','name' => 'Two dimensions','info' => 'Two dimensions'),
  array('topic_id' => 'UKH','subject_id' => 'PHY','name' => 'Kinematics','info' => 'Kinematics'),
  array('topic_id' => 'UMU','subject_id' => 'CHE','name' => 'RADIOACTIVITY','info' => 'RADIOACTIVITY'),
  array('topic_id' => 'Uni','subject_id' => 'PHY','name' => 'General','info' => 'General'),
  array('topic_id' => 'Units','subject_id' => 'PHY','name' => 'General','info' => 'General'),
  array('topic_id' => 'USD','subject_id' => 'CHE','name' => 'Mixed Categories','info' => 'Mixed Categories'),
  array('topic_id' => 'VCR','subject_id' => 'MAT','name' => 'Vectors','info' => 'Vectors'),
  array('topic_id' => 'vec','subject_id' => 'MAT','name' => 'Mixed categories','info' => 'Mixed categories'),
  array('topic_id' => 'VGC','subject_id' => 'CHE','name' => 'PERIODIC PROPERTY','info' => 'PERIODIC PROPERTY'),
  array('topic_id' => 'VHO','subject_id' => 'PHY','name' => 'Electricity & Magnetism','info' => 'Electricity & Magnetism'),
  array('topic_id' => 'VHV','subject_id' => 'CHE','name' => 'THERMOCHEMISTRY','info' => 'THERMOCHEMISTRY'),
  array('topic_id' => 'WEP','subject_id' => 'PHY','name' => 'Work, Energy and Power','info' => 'Work, Energy and Power'),
  array('topic_id' => 'XCV','subject_id' => 'CHE','name' => 'DILUTE SOLUTION AND COLLIGATIVE PROPERTIES','info' => 'DILUTE SOLUTION AND COLLIGATIVE PROPERTIES'),
  array('topic_id' => 'xyz','subject_id' => 'MAT','name' => 'INDEFINITE INTEGRALS','info' => 'INDEFINITE INTEGRALS')
);
